export interface TerminalTheme {
  id: string;
  name: string;
  bg: string;
  fg: string;
  cursor: string;
  selection: string;
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
}

export const THEMES: Record<string, TerminalTheme> = {
  onedark: {
    id: "onedark",
    name: "One Dark",
    bg: "#282c34",
    fg: "#abb2bf",
    cursor: "#528bff",
    selection: "#3e4451aa",
    black: "#282c34",
    red: "#e06c75",
    green: "#98c379",
    yellow: "#e5c07b",
    blue: "#61afef",
    magenta: "#c678dd",
    cyan: "#56b6c2",
    white: "#abb2bf",
    brightBlack: "#5c6370",
    brightRed: "#e06c75",
    brightGreen: "#98c379",
    brightYellow: "#e5c07b",
    brightBlue: "#61afef",
    brightMagenta: "#c678dd",
    brightCyan: "#56b6c2",
    brightWhite: "#ffffff",
  },
  dracula: {
    id: "dracula",
    name: "Dracula",
    bg: "#282a36",
    fg: "#f8f8f2",
    cursor: "#f8f8f2",
    selection: "#44475a99",
    black: "#21222c",
    red: "#ff5555",
    green: "#50fa7b",
    yellow: "#f1fa8c",
    blue: "#bd93f9",
    magenta: "#ff79c6",
    cyan: "#8be9fd",
    white: "#f8f8f2",
    brightBlack: "#6272a4",
    brightRed: "#ff6e6e",
    brightGreen: "#69ff94",
    brightYellow: "#ffffa5",
    brightBlue: "#d6acff",
    brightMagenta: "#ff92df",
    brightCyan: "#a4ffff",
    brightWhite: "#ffffff",
  },
  solarized: {
    id: "solarized",
    name: "Solarized Dark",
    bg: "#002b36",
    fg: "#839496",
    cursor: "#93a1a1",
    selection: "#07364299",
    black: "#073642",
    red: "#dc322f",
    green: "#859900",
    yellow: "#b58900",
    blue: "#268bd2",
    magenta: "#d33682",
    cyan: "#2aa198",
    white: "#eee8d5",
    brightBlack: "#586e75",
    brightRed: "#cb4b16",
    brightGreen: "#859900",
    brightYellow: "#b58900",
    brightBlue: "#268bd2",
    brightMagenta: "#d33682",
    brightCyan: "#2aa198",
    brightWhite: "#fdf6e3",
  },
  gruvbox: {
    id: "gruvbox",
    name: "Gruvbox Dark",
    bg: "#282828",
    fg: "#ebdbb2",
    cursor: "#ebdbb2",
    selection: "#3c3836aa",
    black: "#282828",
    red: "#cc241d",
    green: "#98971a",
    yellow: "#d79921",
    blue: "#458588",
    magenta: "#b16286",
    cyan: "#689d6a",
    white: "#a89984",
    brightBlack: "#928374",
    brightRed: "#fb4934",
    brightGreen: "#b8bb26",
    brightYellow: "#fabd2f",
    brightBlue: "#83a598",
    brightMagenta: "#d3869b",
    brightCyan: "#8ec07c",
    brightWhite: "#ebdbb2",
  },
  vscode: {
    id: "vscode",
    name: "VS Code Dark",
    bg: "#1e1e1e",
    fg: "#d4d4d4",
    cursor: "#aeafad",
    selection: "#264f7899",
    black: "#000000",
    red: "#cd3131",
    green: "#0dbc79",
    yellow: "#e5e510",
    blue: "#2472c8",
    magenta: "#bc3fbc",
    cyan: "#11a8cd",
    white: "#e5e5e5",
    brightBlack: "#666666",
    brightRed: "#f14c4c",
    brightGreen: "#23d18b",
    brightYellow: "#f5f543",
    brightBlue: "#3b8eea",
    brightMagenta: "#d670d6",
    brightCyan: "#29b8db",
    brightWhite: "#ffffff",
  },
  nord: {
    id: "nord",
    name: "Nord",
    bg: "#2e3440",
    fg: "#d8dee9",
    cursor: "#d8dee9",
    selection: "#434c5eaa",
    black: "#3b4252",
    red: "#bf616a",
    green: "#a3be8c",
    yellow: "#ebcb8b",
    blue: "#81a1c1",
    magenta: "#b48ead",
    cyan: "#88c0d0",
    white: "#e5e9f0",
    brightBlack: "#4c566a",
    brightRed: "#bf616a",
    brightGreen: "#a3be8c",
    brightYellow: "#ebcb8b",
    brightBlue: "#81a1c1",
    brightMagenta: "#b48ead",
    brightCyan: "#8fbcbb",
    brightWhite: "#eceff4",
  },
  tokyonight: {
    id: "tokyonight",
    name: "Tokyo Night",
    bg: "#1a1b26",
    fg: "#c0caf5",
    cursor: "#c0caf5",
    selection: "#283457aa",
    black: "#15161e",
    red: "#f7768e",
    green: "#9ece6a",
    yellow: "#e0af68",
    blue: "#7aa2f7",
    magenta: "#bb9af7",
    cyan: "#7dcfff",
    white: "#a9b1d6",
    brightBlack: "#414868",
    brightRed: "#f7768e",
    brightGreen: "#9ece6a",
    brightYellow: "#e0af68",
    brightBlue: "#7aa2f7",
    brightMagenta: "#bb9af7",
    brightCyan: "#7dcfff",
    brightWhite: "#c0caf5",
  },
  catppuccin: {
    id: "catppuccin",
    name: "Catppuccin Mocha",
    bg: "#1e1e2e",
    fg: "#cdd6f4",
    cursor: "#f5e0dc",
    selection: "#45475aaa",
    black: "#45475a",
    red: "#f38ba8",
    green: "#a6e3a1",
    yellow: "#f9e2af",
    blue: "#89b4fa",
    magenta: "#f5c2e7",
    cyan: "#94e2d5",
    white: "#bac2de",
    brightBlack: "#585b70",
    brightRed: "#f38ba8",
    brightGreen: "#a6e3a1",
    brightYellow: "#f9e2af",
    brightBlue: "#89b4fa",
    brightMagenta: "#f5c2e7",
    brightCyan: "#94e2d5",
    brightWhite: "#a6adc8",
  },
  ayu: {
    id: "ayu",
    name: "Ayu Mirage",
    bg: "#1f2430",
    fg: "#cbccc6",
    cursor: "#ffcc66",
    selection: "#33415eaa",
    black: "#191e2a",
    red: "#ff3333",
    green: "#bae67e",
    yellow: "#ffa759",
    blue: "#73d0ff",
    magenta: "#d4bfff",
    cyan: "#95e6cb",
    white: "#cbccc6",
    brightBlack: "#5c6773",
    brightRed: "#ff3333",
    brightGreen: "#bae67e",
    brightYellow: "#ffa759",
    brightBlue: "#73d0ff",
    brightMagenta: "#d4bfff",
    brightCyan: "#95e6cb",
    brightWhite: "#f0f0f0",
  },
  githubdark: {
    id: "githubdark",
    name: "GitHub Dark",
    bg: "#0d1117",
    fg: "#e6edf3",
    cursor: "#e6edf3",
    selection: "#1f6feb66",
    black: "#484f58",
    red: "#ff7b72",
    green: "#3fb950",
    yellow: "#d29922",
    blue: "#58a6ff",
    magenta: "#bc8cff",
    cyan: "#39c5cf",
    white: "#b1bac4",
    brightBlack: "#6e7681",
    brightRed: "#ffa198",
    brightGreen: "#56d364",
    brightYellow: "#e3b341",
    brightBlue: "#79c0ff",
    brightMagenta: "#d2a8ff",
    brightCyan: "#56d4dd",
    brightWhite: "#f0f6fc",
  },
  material: {
    id: "material",
    name: "Material Dark",
    bg: "#263238",
    fg: "#eeffff",
    cursor: "#ffcc00",
    selection: "#546e7a88",
    black: "#000000",
    red: "#ff5370",
    green: "#c3e88d",
    yellow: "#ffcb6b",
    blue: "#82aaff",
    magenta: "#c792ea",
    cyan: "#89ddff",
    white: "#eeffff",
    brightBlack: "#546e7a",
    brightRed: "#ff5370",
    brightGreen: "#c3e88d",
    brightYellow: "#ffcb6b",
    brightBlue: "#82aaff",
    brightMagenta: "#c792ea",
    brightCyan: "#89ddff",
    brightWhite: "#ffffff",
  },
  nightowl: {
    id: "nightowl",
    name: "Night Owl",
    bg: "#011627",
    fg: "#d6deeb",
    cursor: "#80a4c2",
    selection: "#1d3b53aa",
    black: "#011627",
    red: "#ef5350",
    green: "#22da6e",
    yellow: "#addb67",
    blue: "#82aaff",
    magenta: "#c792ea",
    cyan: "#21c7a8",
    white: "#ffffff",
    brightBlack: "#5f7e97",
    brightRed: "#ef5350",
    brightGreen: "#22da6e",
    brightYellow: "#ffeb95",
    brightBlue: "#82aaff",
    brightMagenta: "#c792ea",
    brightCyan: "#7fdbca",
    brightWhite: "#ffffff",
  },
  monokai: {
    id: "monokai",
    name: "Monokai Pro",
    bg: "#2d2a2e",
    fg: "#fcfcfa",
    cursor: "#fcfcfa",
    selection: "#363537aa",
    black: "#403e41",
    red: "#ff6188",
    green: "#a9dc76",
    yellow: "#ffd866",
    blue: "#78dce8",
    magenta: "#ab9df2",
    cyan: "#78dce8",
    white: "#fcfcfa",
    brightBlack: "#727072",
    brightRed: "#ff6188",
    brightGreen: "#a9dc76",
    brightYellow: "#ffd866",
    brightBlue: "#78dce8",
    brightMagenta: "#ab9df2",
    brightCyan: "#78dce8",
    brightWhite: "#fcfcfa",
  },
  rosepine: {
    id: "rosepine",
    name: "Rosé Pine",
    bg: "#191724",
    fg: "#e0def4",
    cursor: "#ebbcba",
    selection: "#26233aaa",
    black: "#26233a",
    red: "#eb6f92",
    green: "#31748f",
    yellow: "#f6c177",
    blue: "#9ccfd8",
    magenta: "#c4a7e7",
    cyan: "#ebbcba",
    white: "#e0def4",
    brightBlack: "#6e6a86",
    brightRed: "#eb6f92",
    brightGreen: "#31748f",
    brightYellow: "#f6c177",
    brightBlue: "#9ccfd8",
    brightMagenta: "#c4a7e7",
    brightCyan: "#ebbcba",
    brightWhite: "#e0def4",
  },
  synthwave: {
    id: "synthwave",
    name: "Synthwave '84",
    bg: "#241b2f",
    fg: "#f92aad",
    cursor: "#f97e72",
    selection: "#33ffe544",
    black: "#1a1b41",
    red: "#f92aad",
    green: "#8a9fff",
    yellow: "#d0e0ff",
    blue: "#8a9fff",
    magenta: "#f97e72",
    cyan: "#33ffe5",
    white: "#f4f4f4",
    brightBlack: "#5f6caf",
    brightRed: "#f92aad",
    brightGreen: "#8a9fff",
    brightYellow: "#d0e0ff",
    brightBlue: "#8a9fff",
    brightMagenta: "#f97e72",
    brightCyan: "#33ffe5",
    brightWhite: "#f4f4f4",
  },
  everforest: {
    id: "everforest",
    name: "Everforest",
    bg: "#2d353b",
    fg: "#d3c6aa",
    cursor: "#d3c6aa",
    selection: "#3d484daa",
    black: "#4b565c",
    red: "#e67e80",
    green: "#a7c080",
    yellow: "#dbbc7f",
    blue: "#7fbbb3",
    magenta: "#d699b6",
    cyan: "#83c092",
    white: "#d3c6aa",
    brightBlack: "#5c6a73",
    brightRed: "#e67e80",
    brightGreen: "#a7c080",
    brightYellow: "#dbbc7f",
    brightBlue: "#7fbbb3",
    brightMagenta: "#d699b6",
    brightCyan: "#83c092",
    brightWhite: "#fdf6e3",
  },
  onelight: {
    id: "onelight",
    name: "One Light",
    bg: "#fafafa",
    fg: "#383a42",
    cursor: "#526eff",
    selection: "#a5d6ff88",
    black: "#000000",
    red: "#e45649",
    green: "#50a14f",
    yellow: "#c18401",
    blue: "#4078f2",
    magenta: "#a626a4",
    cyan: "#0184bc",
    white: "#a0a1a7",
    brightBlack: "#a0a1a7",
    brightRed: "#e45649",
    brightGreen: "#50a14f",
    brightYellow: "#c18401",
    brightBlue: "#4078f2",
    brightMagenta: "#a626a4",
    brightCyan: "#0184bc",
    brightWhite: "#fafafa",
  },
  solarizedlight: {
    id: "solarizedlight",
    name: "Solarized Light",
    bg: "#fdf6e3",
    fg: "#657b83",
    cursor: "#586e75",
    selection: "#eee8d5aa",
    black: "#073642",
    red: "#dc322f",
    green: "#859900",
    yellow: "#b58900",
    blue: "#268bd2",
    magenta: "#d33682",
    cyan: "#2aa198",
    white: "#eee8d5",
    brightBlack: "#586e75",
    brightRed: "#cb4b16",
    brightGreen: "#859900",
    brightYellow: "#b58900",
    brightBlue: "#268bd2",
    brightMagenta: "#d33682",
    brightCyan: "#2aa198",
    brightWhite: "#fdf6e3",
  },
  githublight: {
    id: "githublight",
    name: "GitHub Light",
    bg: "#ffffff",
    fg: "#1f2328",
    cursor: "#1f2328",
    selection: "#ddf4ff",
    black: "#484f58",
    red: "#cf222e",
    green: "#1a7f37",
    yellow: "#9a6700",
    blue: "#0969da",
    magenta: "#8250df",
    cyan: "#1b7c83",
    white: "#6e7781",
    brightBlack: "#6e7781",
    brightRed: "#cf222e",
    brightGreen: "#1a7f37",
    brightYellow: "#9a6700",
    brightBlue: "#0969da",
    brightMagenta: "#8250df",
    brightCyan: "#1b7c83",
    brightWhite: "#ffffff",
  },
  latte: {
    id: "latte",
    name: "Catppuccin Latte",
    bg: "#eff1f5",
    fg: "#4c4f69",
    cursor: "#dc8a78",
    selection: "#ccd0daaa",
    black: "#5c5f77",
    red: "#d20f39",
    green: "#40a02b",
    yellow: "#df8e1d",
    blue: "#1e66f5",
    magenta: "#ea76cb",
    cyan: "#179299",
    white: "#acb0be",
    brightBlack: "#6c6f85",
    brightRed: "#d20f39",
    brightGreen: "#40a02b",
    brightYellow: "#df8e1d",
    brightBlue: "#1e66f5",
    brightMagenta: "#ea76cb",
    brightCyan: "#179299",
    brightWhite: "#4c4f69",
  },
};

export function toXtermTheme(t: TerminalTheme) {
  return {
    background: t.bg,
    foreground: t.fg,
    cursor: t.cursor,
    selectionBackground: t.selection,
    black: t.black,
    red: t.red,
    green: t.green,
    yellow: t.yellow,
    blue: t.blue,
    magenta: t.magenta,
    cyan: t.cyan,
    white: t.white,
    brightBlack: t.brightBlack,
    brightRed: t.brightRed,
    brightGreen: t.brightGreen,
    brightYellow: t.brightYellow,
    brightBlue: t.brightBlue,
    brightMagenta: t.brightMagenta,
    brightCyan: t.brightCyan,
    brightWhite: t.brightWhite,
  };
}

export const DEFAULT_THEME_ID = "onedark";

function ansi(color: string): string {
  const r = parseInt(color.slice(1, 3), 16);
  const g = parseInt(color.slice(3, 5), 16);
  const b = parseInt(color.slice(5, 7), 16);
  return `38;2;${r};${g};${b}`;
}

export interface ThemeBackendConfig {
  promptUser: string;
  promptDir: string;
  promptSymbol: string;
  lsColors: string;
}

export function getThemeConfig(t: TerminalTheme): ThemeBackendConfig {
  const c = (color: string) => ansi(color);
  return {
    promptUser: t.blue,
    promptDir: t.green,
    promptSymbol: t.yellow,
    lsColors: [
      `di=${c(t.blue)}`,
      `ln=${c(t.cyan)}`,
      `ex=${c(t.green)}`,
      `or=${c(t.red)}`,
      `pi=${c(t.red)}`,
      `so=${c(t.red)}`,
      `bd=${c(t.red)}`,
      `cd=${c(t.red)}`,
      `*.tar=${c(t.red)}`,
      `*.tgz=${c(t.red)}`,
      `*.gz=${c(t.red)}`,
      `*.zip=${c(t.red)}`,
      `*.xz=${c(t.red)}`,
      `*.7z=${c(t.red)}`,
      `*.rar=${c(t.red)}`,
      `*.png=${c(t.magenta)}`,
      `*.jpg=${c(t.magenta)}`,
      `*.jpeg=${c(t.magenta)}`,
      `*.gif=${c(t.magenta)}`,
      `*.svg=${c(t.magenta)}`,
      `*.webp=${c(t.magenta)}`,
      `*.mp3=${c(t.magenta)}`,
      `*.mp4=${c(t.magenta)}`,
      `*.mkv=${c(t.magenta)}`,
      `*.pdf=${c(t.red)}`,
      `*.sh=${c(t.green)}`,
      `*.rs=${c(t.green)}`,
      `*.py=${c(t.green)}`,
      `*.js=${c(t.green)}`,
      `*.ts=${c(t.green)}`,
      `*.html=${c(t.magenta)}`,
      `*.css=${c(t.magenta)}`,
      `*.md=${c(t.blue)}`,
      `*.txt=${c(t.fg)}`,
      `*.json=${c(t.fg)}`,
      `*.yml=${c(t.fg)}`,
      `*.yaml=${c(t.fg)}`,
      `*.log=${c(t.fg)}`,
      `*.db=${c(t.cyan)}`,
      `*.sql=${c(t.cyan)}`,
      `*.lock=${c(t.red)}`,
      `*.o=${c(t.red)}`,
      `*.class=${c(t.red)}`,
    ].join(":"),
  };
}
